$(function () {
  var tableLely = $('#table_id').DataTable(

      {
    data: dataForTable,

    columns: [
        {title: "Customer movexcode", data: 'sfdcustomermovexcode'},
        {title: "Farm License", data: 'sfdfarmlicense' },
        {title: "Eng Name", data: 'sfdfarmname' },
        {title: "T4C Version", data: 'sfdcurrentversion' },
        {title: "Nr robots",data: 'sfdnrrobots' },
        {title: "License type", data: 'LicenseType' },
        {title: "OS data", data: 'WindowsOS' },
        {title: "SQL version", data: 'SqlDB' },
        {title: "SQL Database size, Mb", data: 'SqlDatabaseSizeInMB' }
    ]
    }
);




var newList=$('<div><label>Select column <select name="select_column" id="select_column"><option value="sfdcustomermovexcode">Customer movexcode</option><option value="sfdfarmlicense">Farm License</option><option value="sfdfarmname">Eng Name</option><option value="sfdcurrentversion">T4C Version</option><option value="sfdnrrobots">Nr robots</option><option value="LicenseType">License type</option><option value="WindowsOS">OS data</option><option value="SqlDB">SQL version</option><option value="SqlDatabaseSizeInMB">SQL Database size, Mb</option></select> to copy in clipboard</label></div>');
$('#table_id_length').after(newList);

var columnSelector = 'sfdcustomermovexcode';
$('#select_column').change(function(){console.log($(this).val());});


$('#table_id tbody').on('click', 'tr', function () {
    var dataRow= tableLely.row( this ).data();
    navigator.clipboard.writeText(dataRow[$('#select_column').val()]);
    console.log(dataRow[$('#select_column').val()]);
} );
} );

var dataForTable =  [
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "8EZF2-CCSCV-6JMMF-HEAU9-ZQVYF",
                "sfdcustomermovexcode": "0730000000",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 2,
                "sfdfarmname": "Vladimir Korsun",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows 10 Pro",
                "SqlDB": "Microsoft SQL Server 2014 (SP2-GDR) (KB4505217) - 12.0.5223.6 (X64) \n\tMay 26 2019 20:36:50 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.3 <X64> (Build 19042: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 6289.31
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "3H4MA-Z9RN8-CZNNH-MZ3AW-T2K92",
                "sfdcustomermovexcode": "0730000002",
                "sfdcurrentversion": "3.10.0.6",
                "sfdnrrobots": 4,
                "sfdfarmname": "PKUP Sovhoz Smorgonskiy",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": null,
                "SqlDB": null,
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": null
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "FDMC8-NUDAG-GQMG2-MHR77-5YYLV",
                "sfdcustomermovexcode": "0730000004",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 12,
                "sfdfarmname": "SPK Khotily",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2019 Standard",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2269.0 (X64) \n\tJun 10 2015 03:35:45 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.3 <X64> (Build 17763: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 27907.69
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "62F6N-RTSE9-LJW9K-RDJX7-LYF79",
                "sfdcustomermovexcode": "0730000005",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 4,
                "sfdfarmname": "UP Vitebskoblgaz",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows 10 Pro",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2269.0 (X64) \n\tJun 10 2015 03:35:45 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.3 <X64> (Build 19043: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 665.25
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "MBQAS-KA78G-35NGH-HUJPX-3TDM6",
                "sfdcustomermovexcode": "0730000005",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 12,
                "sfdfarmname": "UP Vitebskoblgaz",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2008 R2 Standard",
                "SqlDB": "Microsoft SQL Server 2008 R2 (SP2) - 10.50.4000.0 (X64) \n\tJun 28 2012 08:36:30 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 23773.56
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "G8543-GDKAH-YLXAX-Q59Y9-S69V4",
                "sfdcustomermovexcode": "0730000005",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 4,
                "sfdfarmname": "UP Vitebskoblgaz",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows 7 Professional",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2269.0 (X64) \n\tJun 10 2015 03:35:45 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 6077.69
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "p46vm-9suvx-xtykw-mc499-9c3ex",
                "sfdcustomermovexcode": "0730000006",
                "sfdcurrentversion": "3.12.18.1",
                "sfdnrrobots": 6,
                "sfdfarmname": "Jsc Lepelskij molochnokons. kombinat",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2008 R2 Standard",
                "SqlDB": "Microsoft SQL Server 2008 R2 (SP2) - 10.50.4000.0 (X64) \n\tJun 28 2012 08:36:30 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)\n",
                "DownloadSpeed": 3.15,
                "UploadSpeed": 0.45,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 12679
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "BZ9WC-J5ET3-FMFBG-QQHZ2-T3Z2F",
                "sfdcustomermovexcode": "0730000006",
                "sfdcurrentversion": "3.12.18.1",
                "sfdnrrobots": 12,
                "sfdfarmname": "Jsc Lepelskij molochnokons. kombinat",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2016 Standard",
                "SqlDB": "Microsoft SQL Server 2008 R2 (SP2) - 10.50.4042.0 (X64) \n\tMar 26 2015 21:18:04 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: )\n",
                "DownloadSpeed": 3.15,
                "UploadSpeed": 0.45,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 28898.44
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "SH3U3-58Q4T-GEVQE-RVAQF-28FKC",
                "sfdcustomermovexcode": "0730000007",
                "sfdcurrentversion": "3.2.7.17",
                "sfdnrrobots": 16,
                "sfdfarmname": "GOUP UKS",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": null,
                "SqlDB": null,
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": null
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "62W2K-M5EC4-3ZSAJ-U8LKA-DJKGC",
                "sfdcustomermovexcode": "0730000009",
                "sfdcurrentversion": "3.12.18.1",
                "sfdnrrobots": 16,
                "sfdfarmname": "SPK Progress-Vertelishki",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2008 R2 Standard",
                "SqlDB": "Microsoft SQL Server 2008 R2 (SP1) - 10.50.2500.0 (X64) \n\tJun 17 2011 00:54:03 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)\n",
                "DownloadSpeed": 20.21,
                "UploadSpeed": 5.06,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 28102.44
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "Z2RB9-86Y2D-X59EC-E776W-57PY2",
                "sfdcustomermovexcode": "0730000010",
                "sfdcurrentversion": "3.12.18.1",
                "sfdnrrobots": 6,
                "sfdfarmname": "SPK Nesvizhskie Ostrovki",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2008 R2 Standard",
                "SqlDB": "Microsoft SQL Server 2008 R2 (SP2) - 10.50.4000.0 (X64) \n\tJun 28 2012 08:36:30 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 12438.75
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "LW4DG-U64S2-HANDF-AGVZ8-B8HFG",
                "sfdcustomermovexcode": "0730000011",
                "sfdcurrentversion": "3.12.8.2",
                "sfdnrrobots": 4,
                "sfdfarmname": "SPK Gorodeya",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2008 R2 Standard",
                "SqlDB": "Microsoft SQL Server 2008 R2 (SP2) - 10.50.4042.0 (X64) \n\tMar 26 2015 21:18:04 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 6836.5
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "b6kyb-j57mr-qdk6g-38zk7-cj8p4",
                "sfdcustomermovexcode": "0730000011",
                "sfdcurrentversion": "3.12.8.2",
                "sfdnrrobots": 4,
                "sfdfarmname": "SPK Gorodeya",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": null,
                "SqlDB": null,
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 6,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": null
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "8G48B-DW89C-4JTP9-WN36W-P4C3V",
                "sfdcustomermovexcode": "0730000012",
                "sfdcurrentversion": "3.7.0.17",
                "sfdnrrobots": 6,
                "sfdfarmname": "SHP Vydreya",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "FarmNoMaintenance",
                "WindowsOS": null,
                "SqlDB": null,
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 15,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": null
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "JHLFP-WF4YY-2X8PC-6C2HY-6QNNA",
                "sfdcustomermovexcode": "0730000013",
                "sfdcurrentversion": "3.7.0.17",
                "sfdnrrobots": 6,
                "sfdfarmname": "GPU NP Pripyatskij",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": null,
                "SqlDB": null,
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": null
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "QYT3E-27R6W-FYTKF-ZPY6C-26ZXU",
                "sfdcustomermovexcode": "0730000014",
                "sfdcurrentversion": "3.7.0.17",
                "sfdnrrobots": 6,
                "sfdfarmname": "OAO Turovschina",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": null,
                "SqlDB": null,
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": null
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "883PJ-EPPV2-U9XWS-9KF26-4XHZK",
                "sfdcustomermovexcode": "0730000015",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 12,
                "sfdfarmname": "RUP Minskenergo fil. Lebedevo",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2019 Standard",
                "SqlDB": "Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64) \n\tAug 22 2017 17:04:49 \n\tCopyright (C) 2017 Microsoft Corporation\n\tStandard Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 25688.94
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "CSPNB-MSD6U-JDLHY-QQ53W-VKE95",
                "sfdcustomermovexcode": "0730000016",
                "sfdcurrentversion": "3.12.8.2",
                "sfdnrrobots": 6,
                "sfdfarmname": "GPU NP Belovezhskaya Puscha",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server (R) 2008 Standard",
                "SqlDB": "Microsoft SQL Server 2008 R2 (SP2) - 10.50.4042.0 (Intel X86) \n\tMar 26 2015 21:49:16 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition on Windows NT 6.0 <X86> (Build 6003: Service Pack 2)\n",
                "DownloadSpeed": 4.02,
                "UploadSpeed": 0.48,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 2379.88
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "77J7U-6K9DH-RHWBM-MLAPL-W2JLU",
                "sfdcustomermovexcode": "0730000017",
                "sfdcurrentversion": "3.12.24.2",
                "sfdnrrobots": 16,
                "sfdfarmname": "OAO Alexanderijskoe",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2012 R2 Standard",
                "SqlDB": "Microsoft SQL Server 2014 (SP3-GDR) (KB4583463) - 12.0.6164.21 (X64) \n\tNov  1 2020 04:25:14 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 25540.81
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "FC8N3-NJUDD-P97S8-XHT7B-EDLSF",
                "sfdcustomermovexcode": "0730000018",
                "sfdcurrentversion": "3.12.18.1",
                "sfdnrrobots": 6,
                "sfdfarmname": "RUP Vitebskenergo",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2012 R2 Standard",
                "SqlDB": "Microsoft SQL Server 2008 R2 (SP2) - 10.50.4000.0 (X64) \n\tJun 28 2012 08:36:30 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: )\n",
                "DownloadSpeed": 4.16,
                "UploadSpeed": 0.47,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 5340.25
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "UZVX6-EVZH9-TFA9A-MXH7U-9WCX2",
                "sfdcustomermovexcode": "0730000019",
                "sfdcurrentversion": "3.12.18.1",
                "sfdnrrobots": 16,
                "sfdfarmname": "KUP Minskaya Ovoschnaya Fabrika",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2008 R2 Standard",
                "SqlDB": "Microsoft SQL Server 2008 R2 (SP2) - 10.50.4042.0 (X64) \n\tMar 26 2015 21:18:04 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)\n",
                "DownloadSpeed": 3.95,
                "UploadSpeed": 0.45,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 18895.31
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "6TLZY-YN33K-SFQ6P-ZUTSK-X5GL6",
                "sfdcustomermovexcode": "0730000020",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 10,
                "sfdfarmname": "SPK Agrokombinat Snov",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2019 Standard",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2269.0 (X64) \n\tJun 10 2015 03:35:45 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.3 <X64> (Build 17763: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 16830.19
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "VYZAV-S65H4-M2BG8-W2KW6-U7BBJ",
                "sfdcustomermovexcode": "0730000021",
                "sfdcurrentversion": "3.7.0.15",
                "sfdnrrobots": 1,
                "sfdfarmname": "U.O. Belorusskaya Gosudarstvennaya",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": null,
                "SqlDB": null,
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": null
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "HARG3-JCRBA-LU4DE-DB6Q5-YLJXK",
                "sfdcustomermovexcode": "0730000023",
                "sfdcurrentversion": "3.12.8.2",
                "sfdnrrobots": 2,
                "sfdfarmname": "SP OOO Belita",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows 10 Pro",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2000.8 (X64) \n\tFeb 20 2014 20:04:26 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.3 <X64> (Build 19041: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 3107.44
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "D22ZA-N2GTS-DFNAB-7NWW6-B57CT",
                "sfdcustomermovexcode": "0730000024",
                "sfdcurrentversion": "3.12.18.1",
                "sfdnrrobots": 11,
                "sfdfarmname": "UP Agrokombinat Zhdanovichi",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2008 R2 Standard",
                "SqlDB": "Microsoft SQL Server 2008 R2 (SP2) - 10.50.4000.0 (X64) \n\tJun 28 2012 08:36:30 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)\n",
                "DownloadSpeed": 4.32,
                "UploadSpeed": 1.17,
                "NrOfCosmix": 6,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 13256
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "LTERL-R5KJE-36ZEU-HCXRM-6SX57",
                "sfdcustomermovexcode": "0730000025",
                "sfdcurrentversion": "3.7.0.17",
                "sfdnrrobots": 6,
                "sfdfarmname": "OOO Tarasovo",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": null,
                "SqlDB": null,
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": null
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "du5jl-q5yut-5uc7u-kwwak-nzned",
                "sfdcustomermovexcode": "0730000026",
                "sfdcurrentversion": "3.7.0.15",
                "sfdnrrobots": 3,
                "sfdfarmname": "ZAO \"1 Maja\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": null,
                "SqlDB": null,
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": null
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "7AK3V-F7LZK-T7LU2-F3P3V-5ZKJN",
                "sfdcustomermovexcode": "0730000027",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 2,
                "sfdfarmname": "RUP \"MTZ",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows 10 Pro",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2000.8 (X64) \n\tFeb 20 2014 20:04:26 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.3 <X64> (Build 19042: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 10294
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "Q2MDK-UPJV8-DYJ9F-3LBE9-DW2D2",
                "sfdcustomermovexcode": "0730000028",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 6,
                "sfdfarmname": "OAO \"Dorors\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2008 R2 Standard",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2269.0 (X64) \n\tJun 10 2015 03:35:45 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 11952.75
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "MAXY3-DFEWX-VTFP6-HVW69-VL46R",
                "sfdcustomermovexcode": "0730000029",
                "sfdcurrentversion": "3.11.0.8",
                "sfdnrrobots": 4,
                "sfdfarmname": "CHUP \"ASB Pervaja Vesna\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": null,
                "SqlDB": null,
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": null
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "QJA7S-254SQ-HK5KP-QB5LJ-4NDHJ",
                "sfdcustomermovexcode": "0730000030",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 2,
                "sfdfarmname": "OAO \"Kuhchitsy\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows 7 Professional",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2000.8 (X64) \n\tFeb 20 2014 20:04:26 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": true,
                "SqlDatabaseSizeInMB": 3831.06
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "PG3AA-SLC2B-DNXWJ-XQC4Q-V2EH2",
                "sfdcustomermovexcode": "0730000031",
                "sfdcurrentversion": "3.3.1.18",
                "sfdnrrobots": 6,
                "sfdfarmname": "OAO \"Raps\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": null,
                "SqlDB": null,
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": null
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "QYGZS-RVR6Y-BY8K8-S6ZEM-7UE8W",
                "sfdcustomermovexcode": "0730000032",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 14,
                "sfdfarmname": "OAO 'Gastellovskoe\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2019 Standard",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2269.0 (X64) \n\tJun 10 2015 03:35:45 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.3 <X64> (Build 17763: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 22072.56
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "RJF3P-U9F36-SG2AF-CT9LD-X697F",
                "sfdcustomermovexcode": "0730000033",
                "sfdcurrentversion": "3.12.8.2",
                "sfdnrrobots": 4,
                "sfdfarmname": "OAO \"Krutogorje-Petkovichi\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows 10 Pro",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2000.8 (X64) \n\tFeb 20 2014 20:04:26 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.3 <X64> (Build 14393: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 6270.56
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "BPWAL-T5NBZ-PR9ZZ-HEPLR-ZK3MU",
                "sfdcustomermovexcode": "0730000034",
                "sfdcurrentversion": "3.12.18.1",
                "sfdnrrobots": 2,
                "sfdfarmname": "OAO \"Octayabrskaya Revolucia\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows 7 Ultimate",
                "SqlDB": "Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (X64) \n\tApr  2 2010 15:48:46 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 3708.19
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "YFU42-VC3JZ-VATRZ-3D9Q5-NPABX",
                "sfdcustomermovexcode": "0730000035",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 4,
                "sfdfarmname": "OAO \"Kosino\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows 10 Pro",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2000.8 (X64) \n\tFeb 20 2014 20:04:26 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.3 <X64> (Build 19043: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 7213.5
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "S778H-R824A-57JNW-2KB4J-83U9A",
                "sfdcustomermovexcode": "0730000036",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 2,
                "sfdfarmname": "OAO \"Vilejskij Kombikormovyj Zavod\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows 10 Pro",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2000.8 (X64) \n\tFeb 20 2014 20:04:26 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.3 <X64> (Build 19042: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 3540.88
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "JYW6V-DLL4J-76A3M-53NU9-GFXXH",
                "sfdcustomermovexcode": "0730000037",
                "sfdcurrentversion": "3.3.1.21",
                "sfdnrrobots": 1,
                "sfdfarmname": "GP \"ZhodinoAgroPlemElita\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": null,
                "SqlDB": null,
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": null
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "blbfe-yf4kw-lpdkf-uwtud-rma6r",
                "sfdcustomermovexcode": "0730000038",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 8,
                "sfdfarmname": "OAO \"Jushevichi\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2019 Standard",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2269.0 (X64) \n\tJun 10 2015 03:35:45 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.3 <X64> (Build 17763: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 11864.56
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "H2VSG-U4CSJ-4DCW3-F8RHC-N89W2",
                "sfdcustomermovexcode": "0730000039",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 6,
                "sfdfarmname": "OAO \"Gritskevichi\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2012 R2 Standard",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2000.8 (X64) \n\tFeb 20 2014 20:04:26 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 7008.25
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "JFAQQ-E5HH7-HG5H2-SYQEE-7FWKR",
                "sfdcustomermovexcode": "0730000040",
                "sfdcurrentversion": "3.10.0.9",
                "sfdnrrobots": 10,
                "sfdfarmname": "SHP Voshod",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2008 R2 Standard",
                "SqlDB": "Microsoft SQL Server 2008 R2 (SP2) - 10.50.4042.0 (X64) \n\tMar 26 2015 21:18:04 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 14591
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "A2LMJ-MMXHA-RRDJC-W8CA6-YP8WA",
                "sfdcustomermovexcode": "0730000041",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 8,
                "sfdfarmname": "SHP \"Velikopolje\", KUP \"Minsktrans\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2019 Standard",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2269.0 (X64) \n\tJun 10 2015 03:35:45 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.3 <X64> (Build 17763: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 10018.31
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "DPNM9-VS7K9-4SKYH-KNK8B-W2PKE",
                "sfdcustomermovexcode": "0730000042",
                "sfdcurrentversion": "3.12.15.2",
                "sfdnrrobots": 2,
                "sfdfarmname": "OAO \"Lipovtsy\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows 10 Pro",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2000.8 (X64) \n\tFeb 20 2014 20:04:26 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.3 <X64> (Build 18363: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 1817.88
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "MKWFX-EXDMG-F5HKG-UHBQC-H6PLA",
                "sfdcustomermovexcode": "0730000043",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 10,
                "sfdfarmname": "UP \"Mingaz\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2019 Standard",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2269.0 (X64) \n\tJun 10 2015 03:35:45 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.3 <X64> (Build 17763: )\n",
                "DownloadSpeed": 3.86,
                "UploadSpeed": 0.32,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 14638.94
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "K8WPL-AV8TJ-7F88Y-HW59R-PCJLF",
                "sfdcustomermovexcode": "0730000044",
                "sfdcurrentversion": "3.12.24.2",
                "sfdnrrobots": 3,
                "sfdfarmname": "OAO \"Kaganets\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows 8.1 Pro",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2000.8 (X64) \n\tFeb 20 2014 20:04:26 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 5722.44
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "8NCQR-G9S2F-RD5ES-F29XV-KE65E",
                "sfdcustomermovexcode": "0730000045",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 2,
                "sfdfarmname": "OAO \" Gluboskij Myaskombinat\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows 7 Ultimate",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2269.0 (X64) \n\tJun 10 2015 03:35:45 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 3554.25
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "JFH5W-MSKRH-FJGU7-F8APG-D9SCN",
                "sfdcustomermovexcode": "0730000046",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 12,
                "sfdfarmname": "OAO \"Novoselki Luchaj\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2016 Standard",
                "SqlDB": "Microsoft SQL Server 2014 (SP3-GDR) (KB4583463) - 12.0.6164.21 (X64) \n\tNov  1 2020 04:25:14 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.3 <X64> (Build 14393: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 20975.5
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "DRNE4-A8KTE-VEHBJ-2TP3N-TKZDZ",
                "sfdcustomermovexcode": "0730000047",
                "sfdcurrentversion": "3.7.0.17",
                "sfdnrrobots": 0,
                "sfdfarmname": "OAO \"Poloydkij Molochnyj Kombinat\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": null,
                "SqlDB": null,
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 2,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": null
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "W6NV4-HF32L-2RM2F-562D2-FW8WY",
                "sfdcustomermovexcode": "0730000048",
                "sfdcurrentversion": "3.7.0.17",
                "sfdnrrobots": 4,
                "sfdfarmname": "OAO \"Reshajushij\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": null,
                "SqlDB": null,
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 2,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": null
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "3H75Y-NEJSN-CFVWY-GXYBX-R2TAR",
                "sfdcustomermovexcode": "0730000049",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 7,
                "sfdfarmname": "Minskij Molochnvy Zavod nr. 1",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2012 R2 Standard",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2000.8 (X64) \n\tFeb 20 2014 20:04:26 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 2511.19
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "QBK8S-XPPWL-LU7KF-5747L-9VDCG",
                "sfdcustomermovexcode": "0730000050",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 2,
                "sfdfarmname": "OOO \"Narochanskaya Niva 2004\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows 10 Pro",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2000.8 (X64) \n\tFeb 20 2014 20:04:26 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.3 <X64> (Build 19043: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 3300.69
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "BFRWY-372H9-QLG62-RSGPG-M3EUM",
                "sfdcustomermovexcode": "0730000051",
                "sfdcurrentversion": "3.12.8.2",
                "sfdnrrobots": 2,
                "sfdfarmname": "OAO \"Gluboskij Molochnokonservnyj Ko",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows 7 Professional",
                "SqlDB": "Microsoft SQL Server 2008 R2 (SP2) - 10.50.4042.0 (X64) \n\tMar 26 2015 21:18:04 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 3407.25
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "5S2AF-639GB-VPNNE-8J2F5-7Z834",
                "sfdcustomermovexcode": "0730000053",
                "sfdcurrentversion": "3.12.24.2",
                "sfdnrrobots": 2,
                "sfdfarmname": "OAO Kletskij Kombikormovvj Zavod",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows 7 Ultimate",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2000.8 (X64) \n\tFeb 20 2014 20:04:26 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)\n",
                "DownloadSpeed": 3.29,
                "UploadSpeed": 0.48,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 3116.69
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "BQRGH-E2PND-W7QA3-2PX74-344A6",
                "sfdcustomermovexcode": "0730000054",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 12,
                "sfdfarmname": "OAO \"Orshanskij Miasokonservnyj Komb",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2012 R2 Standard",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2269.0 (X64) \n\tJun 10 2015 03:35:45 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 11952.69
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "TQBK9-PUBML-ETNL6-V6WKK-PWLCE",
                "sfdcustomermovexcode": "0730000055",
                "sfdcurrentversion": "3.12.8.2",
                "sfdnrrobots": 4,
                "sfdfarmname": "KSUP \"Plemennoj Zavod Krasnaya Zvezd",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2008 R2 Standard",
                "SqlDB": "Microsoft SQL Server 2008 R2 (SP2) - 10.50.4042.0 (X64) \n\tMar 26 2015 21:18:04 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 6125
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "88PZF-PQ593-P7R3S-DH686-PDWYZ",
                "sfdcustomermovexcode": "0730000056",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 12,
                "sfdfarmname": "CHPUP \"Uzhitsa Agro\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2016 Standard",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2269.0 (X64) \n\tJun 10 2015 03:35:45 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.3 <X64> (Build 14393: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 0,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 19518.31
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "MSXR2-QSC6M-8CVKE-PGREY-WPMWU",
                "sfdcustomermovexcode": "0730000058",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 8,
                "sfdfarmname": "OAO \"Azot-Agro\"",
                "sfdregion": "Belarus",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2019 Standard",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2269.0 (X64) \n\tJun 10 2015 03:35:45 \n\tCopyright (c) Microsoft Corporation\n\tStandard Edition (64-bit) on Windows NT 6.3 <X64> (Build 17763: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": null,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": false,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 10526.69
            },
            {
                "LceMovexCode": "00301046",
                "LceName": "Lely Center Biocom Technology Ltd.",
                "sfdfarmlicense": "3KRMM-HUHGK-TFZHN-7UCX9-CFA9S",
                "sfdcustomermovexcode": "0750000144",
                "sfdcurrentversion": "3.12.32.2",
                "sfdnrrobots": 9,
                "sfdfarmname": "Ukraine PSP",
                "sfdregion": "(Others)",
                "RobotAvg": 6.5,
                "RobotSum": 379,
                "LicenseType": "Farm",
                "WindowsOS": "Windows Server 2019 Standard",
                "SqlDB": "Microsoft SQL Server 2014 - 12.0.2269.0 (X64) \n\tJun 10 2015 03:35:45 \n\tCopyright (c) Microsoft Corporation\n\tExpress Edition (64-bit) on Windows NT 6.3 <X64> (Build 17763: )\n",
                "DownloadSpeed": null,
                "UploadSpeed": null,
                "NrOfCosmix": 6,
                "NrOfGrazeway": null,
                "HaveVector": false,
                "HaveQwesLD": false,
                "HaveQwesISOLD": false,
                "HaveQwesISOLDReceiver": true,
                "HaveQwesLDN": false,
                "UseInherd": false,
                "SqlDatabaseSizeInMB": 907.38
            }
        ]